defaults: &defaults
  adapter: mysql
  username: twg
  password: twgRulez
  host: localhost

development: &development
  <<: *defaults
  database: jack_lindsey_development

test:
  <<: *defaults
  database: jack_lindsey_test